"""Add password_hash to client for auth

Revision ID: 1f70f891e858
Revises: 525bdf2528bf
Create Date: 2026-07-14 14:58:18.174323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f70f891e858'
down_revision: Union[str, Sequence[str], None] = '525bdf2528bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'password_hash')
    # ### end Alembic commands ###
