"""Add briefing history and stripe client fields

Revision ID: 525bdf2528bf
Revises: 8bc930c92b19
Create Date: 2026-07-14 14:50:37.472525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '525bdf2528bf'
down_revision: Union[str, Sequence[str], None] = '8bc930c92b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('briefing_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('scrape_date', sa.DateTime(), nullable=True),
    sa.Column('insight_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('delivery_status', sa.Enum('SENT', 'FAILED', name='deliverystatus'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefing_history_id'), 'briefing_history', ['id'], unique=False)
    op.add_column('clients', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('slack_webhook_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_clients_stripe_customer_id'), 'clients', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_stripe_customer_id'), table_name='clients')
    op.drop_column('clients', 'slack_webhook_url')
    op.drop_column('clients', 'stripe_customer_id')
    op.drop_index(op.f('ix_briefing_history_id'), table_name='briefing_history')
    op.drop_table('briefing_history')
    # ### end Alembic commands ###
