"""Update Client model

Revision ID: 8bc930c92b19
Revises: 577ec9107109
Create Date: 2026-07-14 12:30:12.201292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc930c92b19'
down_revision: Union[str, Sequence[str], None] = '577ec9107109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email_address', sa.String(), nullable=False))
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email_address'), 'clients', ['email_address'], unique=True)
    op.drop_column('clients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.drop_index(op.f('ix_clients_email_address'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=1)
    op.drop_column('clients', 'is_active')
    op.drop_column('clients', 'email_address')
    # ### end Alembic commands ###
